### ISSUE TITLE
MIT lisence ı kaldır yoksa herkes yaptıklarımızı kopyalayabilir

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [karatasy/ulak-avionic#11]
Lisanssız olsun. Lisanssız olursa kopyalayamazlar. MIT de istediği gibi kopyalama kendisinin gibi değiştirme ve kendisinin deme hakları gibi sınırsız haklar veriyorsun

**Comment by karatasy** [comment]
calinacak diye korkmamiza daha gerek olmadigini dusunuyorum 

ama birazdan kaldiririm mit lisansi
